# docker compose file for productive useage
services:
  postgis:
    image: postgis/postgis:15-3.3-alpine
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    networks:
      - internal
    env_file:
      - ./docker/postgis/.db.env

  mapbender:
    build:
      context: ./
      dockerfile: ./docker/mapbender/Dockerfile
    hostname: "mapbender"
    volumes:
      - type: bind
        source: ./docker/mapbender/bash_scripts
        target: /docker/bash_scripts
      - type: bind
        source: ./
        target: /mapbender
    #   - type: bind
    #     source: ./resources/customconfigs/de-rp/data/conf
    #     target: /data/mapbender/conf
    networks:
      - internal
    env_file:
      - docker/mapbender/.mapbender.env
    depends_on:
      - postgis
    # ports:
    #   - "0.0.0.0:8007:8007"

volumes:
  db-data: null

networks:
  internal: null
